config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'issues#index'
  resources :issues do
    post '/resolve' => 'issues#resolve', as: 'resolve'
    get '/resolve' => 'issues#resolve', as: 'resolve_get'
    resource :notes do
    end
  end

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :user
  has_many :notes

  validates :description, presence: true
  validates :tried_description, presence: true
  validates :user_id, presence: true
  validates :resolved, :inclusion => {:in => [true, false]}
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :issue

  validates :issue_id, presence: true
  validates :user_id, presence: true
  validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :issues
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :alert
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @issue = Issue.new
  end

  def create
    @issue = current_user.issues.build(issue_params)
    respond_to do |format|
      format.html do
        if @issue.save
          redirect_to @issue, success: "Your issue has been created."
          # UserMailer.new_problem_email(current_user, @issue).deliver
        else
          redirect_to new_issue_path
        end
      end
      format.js do
        if @issue.save
          render "/issues/new", status: :created
          # UserMailer.new_problem_email(current_user, @issue).deliver
        else
          redirect_to new_issue_path
        end
      end
    end
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def update

  end

  def destroy

  end

  def resolve
    @issue = Issue.find(params[:issue_id])
    if current_user && current_user.id == @issue.user.id
      respond_to do |format|
        format.html do
          @issue.update_attribute(:resolved, true)
          @issue.save
          redirect_to @issue, success: "Your issue has been resolved."
        end
        format.js do
          @issue.update_attribute(:resolved, true)
          @issue.save
          render "/issues/resolve", status: :created
        end
      end
    else
      redirect_to @issue, alert: "You must be the issue owner to resolve"
    # ADD ELSE FLASH
    end
  end

  private

  def issue_params
    params.require(:issue).permit(:description, :tried_description, :user_id, :resolved)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
before_action :authenticate_user!
before_action :set_note, only: [:show, :edit, :update, :destroy]

  def create
    @issue = Issue.find(params[:issue_id])
    @note = @issue.notes.build(note_params)
    @note.user = current_user

    respond_to do |format|
      if @note.save
        format.html { redirect_to issue_path(@issue), success: 'Your note was successfully created.' }
#        format.json { render :show, status :created, location: @note }
        format.js do
          render "/notes/create", status: :created
        end
        # UserMailer.issue_note_email(@note).deliver
      else
        format.html { render :new }
#        format.json { render json: @note.errors, status: ok}
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, success: 'Your note was successfully updated.' }
#        format.json { render :show, status :ok, location: @note }
      else
        format.html { render :edit }
#        format.json { render json: @note.errors, status :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Your note was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private

  def note_params
    params.require(:note).permit(:text, :user_id, :issue_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/issues/_issue.html.erb
<div id="<%= dom_id(issue) %>">
  <table>
    <tbody>
      <tr>
        <td>What's wrong?</td>
        <td>
          <% if issue.description.split.size > 15 %>
            <%= link_to issue.description.split[0...15].join(' '), issue_path(issue) %>
            <%= "..." %>
          <% else %>
            <%= link_to issue.description, issue_path(issue) %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>What have you tried?</td>
        <td><%= issue.tried_description %></td>
      </tr>
      <tr>
        <td>Who are you?</td>
        <td><%= issue.user.email %></td>
      </tr>
      <tr>
        <td>When was this issue created?</td>
        <td><%= issue.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%b. %d, %Y at %l:%M%P") %></td>
      </tr>
    </tbody>
  </table>
  <%= link_to "Resolve", issue_resolve_path(issue.id), remote: true, method: :post, class: :button %>

  <br>
</div>

app/views/issues/_new.html.erb
<h3>Submit your Issue</h3>
<%= simple_form_for @issue, remote: true do |f| %>
  <%= f.input :description, label: 'What is your issue?' %>
  <%= f.input :tried_description, label: 'What have you tried?' %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :resolved, :value => false %>
  <%= f.button :submit, "Create Issue", class: "button" %>
<% end %>

app/views/issues/_resolve.html.erb
<td class="resolved_section">
  <% if @issue.resolved == false %>
    <% status = '<i class="fa fa-exclamation-triangle"></i>&nbsp'.html_safe + " Unresolved"%>
  <% else %>
    <% status = '<i class="fa fa-check"></i>&nbsp'.html_safe + " Resolved"%>
  <% end %>
  <%= status %>
</td>

app/views/issues/index.html.erb
<%= render "issues/new" if user_signed_in? %>
<h3>Issues</h3>
<% @issues = Issue.where(:resolved => false) %>
<% @issues = @issues.sort_by { |i| i.created_at }.reverse! %>
<div id="issues">
  <%= render @issues %>
</div>

app/views/issues/new.html.erb
<h3>Submit your Issue</h3>
<%= simple_form_for @issue do |f| %>
  <%= f.input :description, label: 'What is your issue?' %>
  <%= f.input :tried_description, label: 'What have you tried?' %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :resolved, :value => false %>
  <%= f.button :submit, "Create Issue", class: "button" %>
<% end %>

app/views/issues/new.js.erb
$("#issues").prepend("<%= j render(@issue) %>");
$("#<%= dom_id(@issue) %>").find('*').effect("highlight", {}, 1500);
$(".issue_description textarea").val("")
$(".issue_tried_description textarea").val("")

app/views/issues/resolve.js.erb
$(".resolved_section").replaceWith("<%= j render 'issues/resolve' %>");
$(".resolved_section").effect("highlight", {}, 1500);

$("#<%= dom_id(@issue) %>").fadeOut('slow', function(){
        $(this).remove();
    });

app/views/issues/show.html.erb
<h3>Your Issue</h3>
<table>
  <tbody>
      <tr>
        <td>What's wrong?</td>
        <td><%= @issue.description %></td>
      </tr>
      <tr>
        <td>What have you tried?</td>
        <td><%= @issue.tried_description %></td>
      </tr>
      <tr>
        <td>Who are you?</td>
        <td><%= @issue.user.email%></td>
      </tr>
      <tr>
        <td>Issue status:</td>
        <%= render "issues/resolve" %>
      </tr>
    </tbody>
  </table>
<%= link_to "Resolve", issue_resolve_path(@issue.id), remote: true, method: :post, class: :button %>

<h4>Notes</h4>
<% @notes = @issue.notes %>
<% @notes = @notes.sort_by { |i| i.created_at } %>
<div id="notes">
  <%= render @notes %>
</div>

<h3>Add Note<h3>
  <%= form_for :note, url: issue_notes_path(@issue.id), remote: true do |f| %>
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>
    <p>
      <%= f.button %>
    </p>
  <% end %>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">ProblemHelper</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <% if user_signed_in?%>
      <ul class="right">
        <li><%= link_to "Logout", destroy_user_session_path,  method: :delete  %></li>
      </ul>
    <% else %>
      <ul class="right">
        <li><%= link_to "Register", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      </ul>
    <% end %>


  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "ProblemHelper" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "shared/flash" %>
    <div class="row">
      <div class="small-2 large-2 columns"> </div>
      <div class="small-8 large-10 columns"><%= yield %></div>
      <div class="small-2 large-2 columns"> </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/notes/_note.html.erb
<div id="<%= dom_id(note) %>">
  <p>
    <%= note.text %>
  </p>
  <p>
    - From <%= note.user.email %> on <%= note.created_at.strftime("%b. %d, %Y") %>
  </p>
</div>

app/views/notes/create.js.erb
$("#notes").append("<%= j render(@note) %>");
$("#<%= dom_id(@note) %>").effect("highlight", {}, 1500);
$("#note_text").val("")
binding.pry

app/views/shared/_flash.html.erb
<% [:success, :info, :warning, :alert].each do |flash_type| %>
  <% if flash[flash_type] %>
    <div data-alert class="alert-box <%= flash_type %> radius">
      <%= flash[flash_type] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>